import { v4 as uuidv4 } from 'uuid';

export const data = [
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+1',
    title: 'Morning Coffee',
    description: 'Starting the day with a fresh cup of coffee and planning the day ahead.',
    views: 145,
    likes: 23,
    date: '2023-01-02',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+2',
    title: 'City Walk',
    description: 'A relaxing walk through the city streets discovering new places.',
    views: 212,
    likes: 54,
    date: '2023-01-05',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+3',
    title: 'Sunset View',
    description: 'Captured a beautiful sunset while traveling along the coast.',
    views: 389,
    likes: 140,
    date: '2023-01-09',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+4',
    title: 'Weekend Coding',
    description: 'Spent the weekend experimenting with new TypeScript features.',
    views: 167,
    likes: 46,
    date: '2023-01-12',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+5',
    title: 'Morning Run',
    description: 'An energizing run in the park early in the morning.',
    views: 254,
    likes: 72,
    date: '2023-01-15',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+6',
    title: 'Street Photography',
    description: 'Exploring street photography and capturing spontaneous moments.',
    views: 301,
    likes: 95,
    date: '2023-01-18',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+7',
    title: 'Learning React',
    description: 'Today I practiced hooks and built a small interactive UI.',
    views: 276,
    likes: 88,
    date: '2023-01-21',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+8',
    title: 'Reading Time',
    description: 'Reading an inspiring book about productivity and habits.',
    views: 198,
    likes: 60,
    date: '2023-01-25',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+9',
    title: 'Mountain Trip',
    description: 'A short trip to the mountains with amazing fresh air.',
    views: 420,
    likes: 160,
    date: '2023-02-02',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+10',
    title: 'Workspace Setup',
    description: 'Improved my workspace with better lighting and organization.',
    views: 350,
    likes: 120,
    date: '2023-02-04',
  },

  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+11',
    title: 'Cooking Pasta',
    description: 'Tried a new homemade pasta recipe today.',
    views: 240,
    likes: 75,
    date: '2023-02-07',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+12',
    title: 'Evening Bike Ride',
    description: 'A calm bike ride during sunset along the river.',
    views: 260,
    likes: 82,
    date: '2023-02-10',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+13',
    title: 'UI Design Practice',
    description: 'Practiced designing a minimal mobile interface.',
    views: 330,
    likes: 110,
    date: '2023-02-12',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+14',
    title: 'Photography Gear',
    description: 'Testing a new lens and experimenting with lighting.',
    views: 298,
    likes: 93,
    date: '2023-02-14',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+15',
    title: 'Nature Walk',
    description: 'Enjoying a peaceful walk surrounded by nature.',
    views: 210,
    likes: 65,
    date: '2023-02-18',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+16',
    title: 'JavaScript Tips',
    description: 'Sharing a few useful JavaScript tricks I discovered.',
    views: 370,
    likes: 150,
    date: '2023-02-21',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+17',
    title: 'Minimal Desk',
    description: 'Decluttered my desk for a cleaner workflow.',
    views: 260,
    likes: 78,
    date: '2023-02-24',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+18',
    title: 'Cafe Work',
    description: 'Worked remotely from a cozy cafe downtown.',
    views: 310,
    likes: 105,
    date: '2023-03-01',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+19',
    title: 'New Keyboard',
    description: 'Finally got a mechanical keyboard for coding.',
    views: 415,
    likes: 180,
    date: '2023-03-04',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+20',
    title: 'Weekend Hiking',
    description: 'Hiking through scenic trails outside the city.',
    views: 360,
    likes: 132,
    date: '2023-03-08',
  },

  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+21',
    title: 'Learning CSS Grid',
    description: 'Practicing complex layouts using CSS Grid.',
    views: 280,
    likes: 95,
    date: '2023-03-11',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+22',
    title: 'Creative Writing',
    description: 'Spent some time writing ideas for future projects.',
    views: 190,
    likes: 52,
    date: '2023-03-15',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+23',
    title: 'Morning Routine',
    description: 'Building a healthy and productive morning routine.',
    views: 275,
    likes: 80,
    date: '2023-03-19',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+24',
    title: 'Coffee Beans',
    description: 'Testing different coffee beans and brewing styles.',
    views: 220,
    likes: 66,
    date: '2023-03-21',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+25',
    title: 'Open Source',
    description: 'Contributed to an open source project today.',
    views: 410,
    likes: 170,
    date: '2023-03-25',
  },

  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+26',
    title: 'Coding Night',
    description: 'Late night coding session building a small app.',
    views: 305,
    likes: 102,
    date: '2023-03-29',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+27',
    title: 'Minimal UI',
    description: 'Exploring minimal design principles.',
    views: 260,
    likes: 90,
    date: '2023-04-02',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+28',
    title: 'Park Picnic',
    description: 'Relaxing afternoon picnic with friends.',
    views: 230,
    likes: 70,
    date: '2023-04-05',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+29',
    title: 'Debugging Day',
    description: 'Spent hours debugging a tricky bug.',
    views: 320,
    likes: 110,
    date: '2023-04-09',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+30',
    title: 'Travel Plans',
    description: 'Planning the next travel destination.',
    views: 340,
    likes: 120,
    date: '2023-04-12',
  },

  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+31',
    title: 'New Project',
    description: 'Started working on a brand new side project.',
    views: 380,
    likes: 150,
    date: '2023-04-15',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+32',
    title: 'Healthy Lunch',
    description: 'Prepared a healthy and delicious lunch.',
    views: 210,
    likes: 64,
    date: '2023-04-18',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+33',
    title: 'Night Photography',
    description: 'Trying night photography techniques.',
    views: 295,
    likes: 97,
    date: '2023-04-22',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+34',
    title: 'Music Break',
    description: 'Listening to music while taking a coding break.',
    views: 175,
    likes: 49,
    date: '2023-04-25',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+35',
    title: 'Learning Node',
    description: 'Deep diving into backend with Node.js.',
    views: 360,
    likes: 130,
    date: '2023-04-28',
  },

  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+36',
    title: 'Morning Yoga',
    description: 'Started the morning with a short yoga session.',
    views: 200,
    likes: 60,
    date: '2023-05-02',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+37',
    title: 'Design Inspiration',
    description: 'Collected UI inspiration from modern apps.',
    views: 270,
    likes: 88,
    date: '2023-05-05',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+38',
    title: 'Weekend Market',
    description: 'Visited a local street market full of colors.',
    views: 310,
    likes: 108,
    date: '2023-05-08',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+39',
    title: 'App Prototype',
    description: 'Built a quick prototype for a new idea.',
    views: 330,
    likes: 118,
    date: '2023-05-12',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+40',
    title: 'Late Night Ideas',
    description: 'Sometimes the best ideas come at night.',
    views: 245,
    likes: 74,
    date: '2023-05-15',
  },

  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+41',
    title: 'Frontend Refactor',
    description: 'Refactored a big part of my frontend code.',
    views: 395,
    likes: 160,
    date: '2023-05-18',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+42',
    title: 'Minimal Theme',
    description: 'Experimenting with a clean minimal theme.',
    views: 260,
    likes: 90,
    date: '2023-05-21',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+43',
    title: 'Learning Git',
    description: 'Practicing advanced Git commands.',
    views: 280,
    likes: 96,
    date: '2023-05-24',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+44',
    title: 'Coffee Break',
    description: 'Taking a small coffee break after work.',
    views: 185,
    likes: 50,
    date: '2023-05-27',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+45',
    title: 'Travel Memories',
    description: 'Looking back at photos from past trips.',
    views: 300,
    likes: 100,
    date: '2023-06-01',
  },

  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+46',
    title: 'Clean Code',
    description: 'Reflected on the importance of writing clean code.',
    views: 410,
    likes: 175,
    date: '2023-06-04',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+47',
    title: 'Creative Sketch',
    description: 'Made a quick UI sketch for a new app.',
    views: 230,
    likes: 72,
    date: '2023-06-07',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+48',
    title: 'Morning Energy',
    description: 'Feeling productive and focused today.',
    views: 260,
    likes: 85,
    date: '2023-06-10',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+49',
    title: 'Coding Playlist',
    description: 'Shared my favorite coding music playlist.',
    views: 320,
    likes: 110,
    date: '2023-06-14',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+50',
    title: 'Weekend Relax',
    description: 'Taking time to relax and recharge.',
    views: 210,
    likes: 65,
    date: '2023-06-17',
  },

  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+51',
    title: 'New Ideas',
    description: 'Brainstorming ideas for upcoming projects.',
    views: 345,
    likes: 125,
    date: '2023-06-20',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+52',
    title: 'Tech Reading',
    description: 'Reading articles about new web technologies.',
    views: 275,
    likes: 90,
    date: '2023-06-23',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+53',
    title: 'Refactoring Code',
    description: 'Improving structure and readability of code.',
    views: 300,
    likes: 100,
    date: '2023-06-26',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+54',
    title: 'Evening Chill',
    description: 'Relaxing with music and tea.',
    views: 180,
    likes: 48,
    date: '2023-06-28',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+55',
    title: 'Tech Meetup',
    description: 'Attended a local tech meetup event.',
    views: 390,
    likes: 155,
    date: '2023-07-02',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+56',
    title: 'Quick Prototype',
    description: 'Built a quick working prototype.',
    views: 310,
    likes: 105,
    date: '2023-07-05',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+57',
    title: 'Morning Thoughts',
    description: 'Reflecting on goals and progress.',
    views: 205,
    likes: 61,
    date: '2023-07-08',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+58',
    title: 'Creative Flow',
    description: 'Enjoying a strong creative flow today.',
    views: 260,
    likes: 86,
    date: '2023-07-11',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+59',
    title: 'Late Coding',
    description: 'Working late to finish an important feature.',
    views: 335,
    likes: 120,
    date: '2023-07-15',
  },
  {
    id: uuidv4(),
    img: 'https://placehold.co/600x600?text=Post+60',
    title: 'Project Milestone',
    description: 'Reached an important milestone in my project.',
    views: 450,
    likes: 200,
    date: '2023-07-20',
  },
];
